### ISSUE TITLE
lispsh not found

### ISSUE THREAD

**Issue by spapas** [40ants/run-tests#7]
See for example https://github.com/spapas/web-lisp/actions/runs/11142792617/job/30966491138

I'm using the README yaml for my project: https://github.com/spapas/web-lisp/blob/master/.github/workflows/ci-test.yml

**Comment by svetlyak40wt** [comment]
Seems the instruction in the README is outdates.

Could you please try setup-lisp@v4 instead of v1?

**Comment by spapas** [comment]
That was the problem ty!
